name: Diversity LSC Loader
version: '0.1'

urls:
  - '*://my.logiscool.com/*'

files:
  - name: inject.js
    regex: 'main\..{8}\.chunk\.js'
    source: generated/main.bundle.js

output_folder: extension